version: '3.8'

# Plant Chatbot - Portable Application
#
# Instructions:
# 1. Make sure Docker Desktop is running.
# 2. Create a ".env" file from the "sample.env" template and add your API keys.
# 3. Run 'docker compose up' in your terminal from this folder.
# 4. Open your browser to http://localhost:9697

services:
  backend:
    # Pulls the pre-built, self-contained backend image from Docker Hub.
    image: sora1110/plant-backend:latest
    container_name: plant-backend
    # Injects user-provided API keys from the .env file.
    env_file:
      - .env
    expose:
      - "9696"
    restart: always

  frontend:
    # Pulls the pre-built frontend image from Docker Hub.
    image: sora1110/plant-frontend:latest
    container_name: plant-frontend
    ports:
      - "9697:80"
    restart: always
    depends_on:
      - backend